version: '3.4'

services:
  gw2_guildemblem_cdn.core:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro